[versions]
# Compose
compose = "1.10.0-rc01"
composeHotReload = "1.0.0"

# Kotlin
kotlin = "2.3.0"

# Android
agp = "8.13.2"
android-compileSdk = "36"
android-minSdk = "34"
android-targetSdk = "36"
androidx-activity = "1.12.2"
androidx-core = "1.17.0"

androidx-nav3 = "1.0.0-alpha06"
androidx-nav3-viewModel = "2.10.0-alpha07"
lifecycle-runtime-compose = "2.10.0-alpha07"
androidx-adaptive = "1.3.0-alpha03"

material3 = "1.10.0-alpha05"

kotlinx-serialization = "1.9.0"
kotlinx-coroutines = "1.10.2"
kotlinx-datetime = "0.7.1"
kotlinx-collections-immutable = "0.4.0"
multiplatform-settings = "1.3.0"
uiTiles = "2.21.0"
koin = "4.1.1"
kalendar = "2.9.0"

[libraries]
androidx-activitycompose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity" }
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-nav3-ui = { group = "org.jetbrains.androidx.navigation3", name = "navigation3-ui", version.ref = "androidx-nav3" }
androidx-nav3-viewModel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-navigation3", version.ref = "androidx-nav3-viewModel" }

androidx-material3-adaptive = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive", version.ref = "androidx-adaptive" }
androidx-material3-adaptive-nav3 = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive-navigation3", version.ref = "androidx-adaptive" }

lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle-runtime-compose" }

compose-material3 = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "material3" }

kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
multiplatform-settings = { group = "com.russhwolf", name = "multiplatform-settings", version.ref = "multiplatform-settings" }
multiplatform-settings-no-arg = { group = "com.russhwolf", name = "multiplatform-settings-no-arg", version.ref = "multiplatform-settings" }
alorma-settings-ui-tiles = { group = "com.github.alorma.compose-settings", name = "ui-tiles", version.ref = "uiTiles" }
alorma-settings-ui-tiles-extended = { group = "com.github.alorma.compose-settings", name = "ui-tiles-extended", version.ref = "uiTiles" }

koin-bom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koin" }
koin-core = { group = "io.insert-koin", name = "koin-core" }
koin-android = { group = "io.insert-koin", name = "koin-android" }
koin-compose = { group = "io.insert-koin", name = "koin-compose" }
koin-compose-viewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel" }

kalendar = { group = "com.kizitonwose.calendar", name = "compose-multiplatform", version.ref = "kalendar" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
jetbrains-compose-hotreload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose" }
jetbrains-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
