[versions]
# Compose
compose = "1.10.0-rc02"

# Kotlin
kotlin = "2.3.0"
ksp = "2.3.4"

# Android
agp = "8.13.2"
android-compileSdk = "36"
android-minSdk = "35"
android-targetSdk = "36"
androidx-activity = "1.12.2"
androidx-appcompat = "1.7.0"
androidx-core = "1.17.0"
androidx-work = "2.11.0"

androidx-nav3 = "1.0.0-alpha06"
androidx-nav3-viewModel = "2.10.0-alpha07"
lifecycle-runtime-compose = "2.10.0-alpha07"
androidx-adaptive = "1.3.0-alpha03"

material3 = "1.10.0-alpha05"

kotlinx-serialization = "1.9.0"
kotlinx-datetime = "0.7.1"
kotlinx-collections-immutable = "0.4.0"
multiplatform-settings = "1.3.0"
room = "2.8.4"
sqlite = "2.6.2"
uiTiles = "2.23.0"
koin = "4.1.1"
kalendar = "2.9.0"

materialKolor = "5.0.0-alpha04"

scanEngine = "1.6.2"

[libraries]
androidx-activitycompose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidx-work" }
androidx-nav3-ui = { group = "org.jetbrains.androidx.navigation3", name = "navigation3-ui", version.ref = "androidx-nav3" }
androidx-nav3-viewModel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-navigation3", version.ref = "androidx-nav3-viewModel" }

androidx-material3-adaptive = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive", version.ref = "androidx-adaptive" }
androidx-material3-adaptive-nav3 = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive-navigation3", version.ref = "androidx-adaptive" }

lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle-runtime-compose" }

compose-material3 = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "material3" }

kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
multiplatform-settings = { group = "com.russhwolf", name = "multiplatform-settings", version.ref = "multiplatform-settings" }
multiplatform-settings-no-arg = { group = "com.russhwolf", name = "multiplatform-settings-no-arg", version.ref = "multiplatform-settings" }

alorma-settings-ui-base = { group = "com.github.alorma.compose-settings", name = "ui-base", version.ref = "uiTiles" }
alorma-settings-ui-tiles = { group = "com.github.alorma.compose-settings", name = "ui-tiles", version.ref = "uiTiles" }
alorma-settings-ui-tiles-extended = { group = "com.github.alorma.compose-settings", name = "ui-tiles-extended", version.ref = "uiTiles" }
alorma-settings-ui-tiles-expressive = { group = "com.github.alorma.compose-settings", name = "ui-tiles-expressive", version.ref = "uiTiles" }

koin-bom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koin" }
koin-compose = { group = "io.insert-koin", name = "koin-compose" }
koin-compose-viewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel" }
koin-androidx-workmanager = { group = "io.insert-koin", name = "koin-androidx-workmanager" }

kalendar = { group = "com.kizitonwose.calendar", name = "compose-multiplatform", version.ref = "kalendar" }

androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }

androidx-sqlite-bundled = { group = "androidx.sqlite", name = "sqlite-bundled", version.ref = "sqlite" }
androidx-room-sqlite-wrapper = { group = "androidx.room", name = "room-sqlite-wrapper", version.ref = "room" }

compose-runtime = { group = "org.jetbrains.compose.runtime", name = "runtime", version.ref = "compose" }
compose-ui = { group = "org.jetbrains.compose.ui", name = "ui", version.ref = "compose" }
compose-components-resources = { group = "org.jetbrains.compose.components", name = "components-resources", version.ref = "compose" }
compose-foundation = { group = "org.jetbrains.compose.foundation", name = "foundation", version.ref = "compose" }
compose-ui-tooling-preview = { group = "org.jetbrains.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
compose-ui-tooling = { group = "org.jetbrains.compose.ui", name = "ui-tooling", version.ref = "compose" }

material-kolor = { group = "com.materialkolor", name = "material-kolor", version.ref = "materialKolor" }

scan-engine = { group = "com.github.tillhub", name = "scan-engine", version.ref = "scanEngine" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose" }
jetbrains-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-Android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
androidx-room = { id = "androidx.room", version.ref = "room" }
